name: ${{values.app_name}}-cicd

on:
  push:
    paths:
      - src/**
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:

      - name: Shorten commit id
        shell: bash
        run: |
          echo "COMMIT_ID=${GITHUB_SHA::6}" >> "$GITHUB_ENV"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ '${{ secrets.DOCKERHUB_USERNAME }}'  }}
          password: ${{ '${{ secrets.DOCKERHUB_TOKEN }}' }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: madjava/${{values.app_name}}:${{ '${{ env.COMMIT_ID }}' }}
    outputs:
      commit_id: ${{ '${{ env.COMMIT_ID }}' }}

  cd:
    needs: ci
    runs-on: self-hosted
    steps:

      - uses: actions/checkout@v3
     
      - name: Install Libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip yq
      
      - name: Modify values file
        shell: bash
        run: |
          echo ${{ '${{needs.ci.outputs.commit_id}}' }}
          yq -Yi '.image.tag = "${{ '${{needs.ci.outputs.commit_id}}' }}"' charts/${{values.app_name}}/values-${{values.app_env}}.yaml

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Updates values.yaml with commit ${{ '${{needs.ci.outputs.commit_id}}' }}'

      - name: Install ArgoCD
        shell: bash
        run: |
          curl -ksSL -o argocd https://argocd-server.argocd/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv ./argocd /usr/local/bin/argocd
      
      - name: Login to ArgoCD
        shell: bash
        run: |
          argocd login ${{ '${{ secrets.ARGOCD_SERVER }}' }} \
            --username ${{ '${{ secrets.ARGOCD_USERNAME }}' }} \
            --password ${{ '${{ secrets.ARGOCD_PASSWORD }}' }} \
            --grpc-web \
            --insecure

      - name: Create App in ArgoCD
        shell: bash
        run: |          
          # Connect the ArgoCD repo if not already connected
          repo=https://github.com/partedwaves/${{values.app_name}}.git
          argocd repo list | grep  -q $repo || argocd repo add $repo

          # Create the ArgoCD app if it does not exist
          argocd app get ${{values.app_name}} || argocd app create ${{values.app_name}} \
            --repo $repo \
            --path charts/${{values.app_name}} \
            --dest-server https://kubernetes.default.svc \
            --dest-namespace ${{values.app_env}} \
            --values values-${{values.app_env}}.yaml \
            --revision main \
            --sync-policy manual \
            --sync-option CreateNamespace=true
      
      - name: ArgoCD App Sync
        shell: bash
        run: |
          argocd app sync ${{values.app_name}}
          argocd app wait ${{values.app_name}} --timeout 180
